# Generated by Django 5.2.3 on 2025-07-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contains_label", models.BooleanField()),
                ("pallet_condition", models.BooleanField()),
                ("boxes_organization", models.BooleanField()),
                ("batch_removal", models.DateTimeField()),
                ("observation", models.TextField()),
                ("correction", models.TextField()),
                ("fraction", models.IntegerField(blank=True, null=True)),
                ("amount_default", models.IntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
