# Generated by Django 5.2.3 on 2025-07-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnHoldPalletReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hold_reason",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_AGIN_DAT", "Aguardando AGIN/DAT"),
                            ("AGUARDANDO_OP", "Aguardando OP"),
                            (
                                "AGUARDANDO_DESVIO_ENGENHARIA",
                                "Aguardando Desvio de Engenharia",
                            ),
                            ("AGUARDANDO_RESULTADO_ORT", "Aguardando Resultado ORT"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=100,
                    ),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RejectedPalletReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.TextField()),
                ("qrqc_failure", models.IntegerField(blank=True, null=True)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("REVISAO_PRODUCAO", "Revisão Produção"),
                            ("REINSPECAO_QUALIDADE", "Reinspeção Qualidade"),
                            ("QRQC_FALHA", "QRQC/Falha"),
                            ("PROCESSO_DESBLOQUEIO", "Processo Desbloqueio"),
                        ],
                        max_length=100,
                    ),
                ),
                ("steps_completed", models.BooleanField()),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleasedPalletReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_box", models.IntegerField()),
                ("last_box", models.IntegerField()),
                ("images", models.JSONField(blank=True, default=list)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WipReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contains_label", models.BooleanField()),
                ("pallet_condition", models.BooleanField()),
                ("boxes_organization", models.BooleanField()),
                ("batch_removal", models.DateTimeField()),
                ("observation", models.TextField()),
                ("correction", models.TextField()),
                ("fraction", models.IntegerField(blank=True, null=True)),
                ("amount_default", models.IntegerField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
