# Generated by Django 5.2.3 on 2025-07-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PalletInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("quantity", models.IntegerField()),
                ("work_order", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_address", models.CharField(max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INSPECTION", "Inspection"),
                            ("WIP", "Work In Progress"),
                            ("STORAGE", "Storage"),
                            ("RETURN", "Return"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_pallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pallets",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
