# Generated by Django 5.2.3 on 2025-07-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PalletSticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("encoding", models.CharField(max_length=255)),
                ("mimetype", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("file_path", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PalletInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("quantity", models.IntegerField()),
                ("work_order", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_address", models.CharField(max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INSPECTION", "Inspection"),
                            ("WIP", "Work In Progress"),
                            ("STORAGE", "Storage"),
                            ("RETURN", "Return"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_pallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pallets",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnHoldPallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hold_reason",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_AGIN_DAT", "Aguardando AGIN/DAT"),
                            ("AGUARDANDO_OP", "Aguardando OP"),
                            (
                                "AGUARDANDO_DESVIO_ENGENHARIA",
                                "Aguardando Desvio de Engenharia",
                            ),
                            ("AGUARDANDO_RESULTADO_ORT", "Aguardando Resultado ORT"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=100,
                    ),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RejectedPallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.TextField()),
                ("qrqc_failure", models.IntegerField(blank=True, null=True)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("REVISAO_PRODUCAO", "Revisão Produção"),
                            ("REINSPECAO_QUALIDADE", "Reinspeção Qualidade"),
                            ("QRQC_FALHA", "QRQC/Falha"),
                            ("PROCESSO_DESBLOQUEIO", "Processo Desbloqueio"),
                        ],
                        max_length=100,
                    ),
                ),
                ("steps_completed", models.BooleanField()),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleasedPallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_box", models.IntegerField()),
                ("last_box", models.IntegerField()),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pallets.palletinfo",
                    ),
                ),
            ],
        ),
    ]
